const QUESTION = {
  REQUEST: 'QUESTION_REQUEST',
  REQUEST_SUCCESS: 'QUESTION_REQUEST_SUCCESS',
  REQUEST_FAILED: 'QUESTION_REQUEST_FAILED',
};

const ANSWER = {
  REQUEST: 'ANSWER_REQUEST',
  REQUEST_SUCCESS: 'ANSWER_REQUEST_SUCCESS',
  REQUEST_FAILED: 'ANSWER_REQUEST_FAILED',
};

export {
  QUESTION,
  ANSWER,
};
